# Generated by Django 5.2.14 on 2026-06-17 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("drones", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Detection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_type",
                    models.CharField(
                        choices=[
                            ("PERSON", "Person"),
                            ("CAR", "Car"),
                            ("TRUCK", "Truck"),
                            ("BUS", "Bus"),
                            ("MOTORBIKE", "Motorbike"),
                        ],
                        max_length=30,
                    ),
                ),
                ("confidence", models.FloatField()),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("image_path", models.CharField(max_length=300)),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "drone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="drones.drone"
                    ),
                ),
            ],
        ),
    ]
