# Generated by Django 5.2.14 on 2026-06-02 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("drones", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Telemetry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("altitude", models.FloatField()),
                ("speed", models.FloatField()),
                ("battery_level", models.IntegerField()),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "drone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telemetry_logs",
                        to="drones.drone",
                    ),
                ),
            ],
        ),
    ]
