# Generated by Django 5.2.14 on 2026-06-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telemetry", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="telemetry",
            name="battery_level",
        ),
        migrations.AddField(
            model_name="telemetry",
            name="area",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AddField(
            model_name="telemetry",
            name="battery_percentage",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="telemetry",
            name="direction",
            field=models.CharField(default="Unknown", max_length=50),
        ),
        migrations.AddField(
            model_name="telemetry",
            name="network_signal_strength",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="telemetry",
            name="temperature",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="telemetry",
            name="altitude",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="telemetry",
            name="latitude",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="telemetry",
            name="longitude",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="telemetry",
            name="speed",
            field=models.FloatField(default=0),
        ),
    ]
